CREATE DATABASE  IF NOT EXISTS `BOOKSHOP` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `BOOKSHOP`;
--
-- Table book
--
DROP TABLE IF EXISTS `BOOK`;
CREATE TABLE BOOK (
	ISBN 		VARCHAR(50) NOT NULL,
	BOOK_NAME	VARCHAR(100) NOT NULL,
	PRICE		INT,
	PRIMARY KEY (ISBN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--
-- Table book_stock
--
DROP TABLE IF EXISTS `BOOK_STOCK`;
CREATE TABLE BOOK_STOCK (
	ISBN 		VARCHAR(50) NOT NULL,
	STOCK		INT,
	PRIMARY KEY (ISBN),
	CHECK(STOCK > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--
-- Table account
--
DROP TABLE IF EXISTS `ACCOUNT`;
CREATE TABLE ACCOUNT (
	USERNAME 	VARCHAR(50) NOT NULL,
	BALANCE		INT NOT NULL,
	PRIMARY KEY (USERNAME),
	CHECK(BALANCE >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;